export default [
  {
    id: 1,
    title: "Life lessons with Katie Zaferes",
    description: "",
    price: 135,
    coverImg: "swimmer.png",
    stats: {
      rating: 5.0,
      reviewCount: 15,
    },
    location: "Online",
    openSpots: 0,
  },
  {
    id: 2,
    title: "Learn wedding photography",
    description: "",
    price: 125,
    coverImg: "wedding-pic.jpg",
    stats: {
      rating: 5.0,
      reviewCount: 30,
    },
    location: "Online",
    openSpots: 28,
  },
  {
    id: 3,
    title: "Group Mountain Biking",
    description: "",
    price: 55,
    coverImg: "mountain-bike1.png",
    stats: {
      rating: 4.8,
      reviewCount: 29,
    },
    location: "USA",
    openSpots: 10,
  },
  {
    id: 4,
    title: "Life lessons with Katie Zaferes",
    description: "",
    price: 135,
    coverImg: "swimmer.png",
    stats: {
      rating: 5.0,
      reviewCount: 15,
    },
    location: "Online",
    openSpots: 0,
  },
  {
    id: 5,
    title: "Learn wedding photography",
    description: "",
    price: 125,
    coverImg: "wedding-pic.jpg",
    stats: {
      rating: 5.0,
      reviewCount: 30,
    },
    location: "Online",
    openSpots: 28,
  },
  {
    id: 6,
    title: "Group Mountain Biking",
    description: "",
    price: 55,
    coverImg: "mountain-bike1.png",
    stats: {
      rating: 4.8,
      reviewCount: 29,
    },
    location: "INDIA",
    openSpots: 10,
  },
];
